Add missing requests package
When you try `./geozones.py`, you get below error in a virtual environment

```
Traceback (most recent call last):
  File "./geozones.py", line 18, in <module>
    import france  # noqa
  File "/home/thomas/git/geozones/france.py", line 7, in <module>
    from dbpedia import DBPedia
  File "/home/thomas/git/geozones/dbpedia.py", line 1, in <module>
    import requests
ImportError: No module named 'requests'
```
I've confirmed the dependency to `requests` at https://github.com/etalab/geozones/blob/master/dbpedia.py.
I choose to solve the dependencies by adding the lib in current edited file instead of trying to solve it switching to the standard `urllib` module.